version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '21:00'
    allow:
      - dependency-type: 'all'
    commit-message:
      prefix: 'npm'
    open-pull-requests-limit: 10
    target-branch: 'develop'
    labels:
      - 'npm dependencies'
    versioning-strategy: 'increase-if-necessary'
