version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "npm"
    open-pull-requests-limit: 0
    target-branch: "develop"
    labels:
      - "npm dependencies"
    version_requirement_updates: "increase-if-necessary"
