language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "10"
  - "9"
  - "8"
  - "7"

script:
  - yarn
  - npm run build
  - now --prod

# safelist
branches:
  only:
    - master
