language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - "11"
  - "10"

script:
  - yarn
  - yarn test
  - npm run build
  - now --prod

# safelist
branches:
  only:
    - master
